//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACycle.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppChangelogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppChangelogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACycle.Resources.Strings.AppChangelogs", typeof(AppChangelogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial version of ACycle..
        /// </summary>
        public static string v1_0_0_1 {
            get {
                return ResourceManager.GetString("v1.0.0.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial store version of ACycle..
        /// </summary>
        public static string v1_0_1_0 {
            get {
                return ResourceManager.GetString("v1.0.1.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary editing is now stable..
        /// </summary>
        public static string v1_0_2_0 {
            get {
                return ResourceManager.GetString("v1.0.2.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add database migration tool.\nDatabase migration from godot version of ACycle is now possible..
        /// </summary>
        public static string v1_0_3_0 {
            get {
                return ResourceManager.GetString("v1.0.3.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilize database migration..
        /// </summary>
        public static string v1_0_3_1 {
            get {
                return ResourceManager.GetString("v1.0.3.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store version of v1.0.3.1..
        /// </summary>
        public static string v1_0_4_0 {
            get {
                return ResourceManager.GetString("v1.0.4.0", resourceCulture);
            }
        }
    }
}
