//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACycle.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACycle.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string AppShell_Activity {
            get {
                return ResourceManager.GetString("AppShell_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string AppShell_Debugging {
            get {
                return ResourceManager.GetString("AppShell_Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        public static string AppShell_Diary {
            get {
                return ResourceManager.GetString("AppShell_Diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string AppShell_Focus {
            get {
                return ResourceManager.GetString("AppShell_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string AppShell_Health {
            get {
                return ResourceManager.GetString("AppShell_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger.
        /// </summary>
        public static string AppShell_Ledger {
            get {
                return ResourceManager.GetString("AppShell_Ledger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        public static string AppShell_Planning {
            get {
                return ResourceManager.GetString("AppShell_Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AppShell_Settings {
            get {
                return ResourceManager.GetString("AppShell_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App Data Directory in File Explorer.
        /// </summary>
        public static string DebuggingView_OpenAppDirectory {
            get {
                return ResourceManager.GetString("DebuggingView_OpenAppDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging Options.
        /// </summary>
        public static string DebuggingView_Title {
            get {
                return ResourceManager.GetString("DebuggingView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        public static string DiaryView_Title {
            get {
                return ResourceManager.GetString("DiaryView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsView_Language {
            get {
                return ResourceManager.GetString("SettingsView_Language", resourceCulture);
            }
        }
    }
}
